In [4]:
import numpy as np

In [7]:
array_1d = np.array([1, 2, 3, 4, 5])
print(array_1d.ndim) # Número de dimensiones
print(array_1d.shape) # Forma del array (número de elementos en cada dimensión)
print(array_1d)

1
(5,)
[1 2 3 4 5]


In [ ]:
array_2d = np.array([[1, 2, 3], [4, 5, 6]])
print(array_2d.ndim) # Número de dimensiones    
print(array_2d.shape) # Forma del array (número de elementos en cada dimensión)
print(array_2d)
# Matrizes, tabelas de dados, imagens em escala de cinza

2
(2, 3)
[[1 2 3]
 [4 5 6]]


In [ ]:
array_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(array_3d.ndim) # Número de dimensiones    
print(array_3d.shape) # Forma del array (número de elementos en cada dimensión)
print(array_3d)


3
(2, 2, 2)
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
